### ISSUE TITLE
Triggering animation after clicking

### ISSUE THREAD

**Issue by DmitrySharikov** [dcdeiv/simpler-sidebar#10]
Hello everyone.

I have some issue with triggering animation. When I click somewhere, sidebar is always closing, even if it's not link(just a div or another one element)

here is my code:

```
$(document).ready(function(){

  $('#link-list').simplerSidebar({
    opener: '#links-menu',
    sidebar: {
      align: 'right',
      width: 300,
      closingLinks: '.fa-angle-left'
    }
  });

  $('#cart-list').simplerSidebar({
    opener: '#cart-menu',
    sidebar: {
      align: 'right',
      width: 300,
      closingLinks: '.fa-angle-left'
    }
  });

  $('#search-list').simplerSidebar({
    opener: '#search-menu',
    sidebar: {
      align: 'right',
      width: 300,
      closingLinks: '.fa-angle-left'
    }
  });
});
```
p.s. opening sidebar works fine

**Comment by dcdeiv** [comment]
So you have three sidebars? If so I've never tested more than one sidebar at once. But I guess that there won't be any problem since demos works just fine with only one.
Have you updated the plug-in? [update here](https://github.com/dcdeiv/simpler-sidebar/releases/tag/v1.4.0) or run `bower update` if you downloaded the package with Bower.

[static-left](http://dcdeiv.github.io/simpler-sidebar/development/tests/static-left.html)
[static-right](http://dcdeiv.github.io/simpler-sidebar/development/tests/static-right.html)
[static-left-top](http://dcdeiv.github.io/simpler-sidebar/development/tests/static-left-top.html)
[static-right-top](http://dcdeiv.github.io/simpler-sidebar/development/tests/static-right-top.html)

In this demos the plugin works fine. Have you followed the instructions? [getting started](http://dcdeiv.github.io/simpler-sidebar/#getting-started).

**Comment by DmitrySharikov** [comment]
> So you have three sidebars?
yep
Have you updated the plug-in?
and this is solution!

thx for helping and for this awesome plugin

**Comment by dcdeiv** [comment]
You're wellcome!
