### ISSUE TITLE
Mask over the sidebar

### ISSUE THREAD

**Issue by cope** [dcdeiv/simpler-sidebar#12]
I used the basic example with the sidebar-wrapper, but when the sidebar opens, the mask is over it. I made just a few simple links in the sidebar, but the cursor does not change when I hover them and onclick the sidebar simply closes, the links are not clicked...

This is the code I use:

    $('#sidebar').simplerSidebar({
    	top: 0,
    	opener: '#toggle-sidebar',
    	attr: 'simplersidebar',
    	animation: {
    		easing: 'easeOutQuint'
    	},
    	sidebar: {
    		align: 'left',
    		width: 300,
    		closingLinks: '.close-sidebar',
    	}
    });

    <div id="sidebar">
        <div id="sidebar-wrapper" class="sidebar-wrapper">
            <table width="100%" height="100%" border="0" class="close-sidebar">
                <tr>
                    <td align="center" valign="middle">
                        <a href="http://google.com" target="_blank">google</a><br /><br />
                        <a href="http://google.com" target="_blank">google</a><br /><br />
                        <a href="http://google.com" target="_blank">google</a><br /><br />
                        <a href="http://google.com" target="_blank">google</a>
                    </td>
                </tr>
            </table>
        </div>
    </div>

But in general, the z-index of the sidebar element seams to be messed up. Some of the page elements are over it even though they have a smaller z-index.

I am using it inside a Meteor app, and this may have something to do with it :(
For example, a new mask div is created over and over everytime I open the page where the sidebar should exist.

**Comment by dcdeiv** [comment]
Have you downloaded the lates version of the plugin? Be sure to have followed the [instructions](https://github.com/dcdeiv/simpler-sidebar#getting-started). And if this might help you, use of these [test](https://github.com/dcdeiv/simpler-sidebar/tree/master/tests) pages which works as they should.

The plugin is not meant to change the cursor while hovering a link, you should [tweak it in your css](https://developer.mozilla.org/it/docs/Web/CSS/cursor).

Did you added in you CSS this style attributes for `.sidebar-wrapper`?
```css
.sidebar-wrapper {
    position: relative;
    height: 100%;
    overflow: auto;
}
```

You are using `.close-sidebar` in the wrong way. As in the [guide](https://github.com/dcdeiv/simpler-sidebar#getting-started), the `closingLinks` method must be attached to links, not to tables:

```html
<table width="100%" height="100%" border="0">
    <tr>
	<td align="center" valign="middle">
	    <a class="close-sidebar" href="http://google.com" target="_blank">google</a><br /><br />
	    <a class="close-sidebar" href="http://google.com" target="_blank">google</a><br /><br />
	    <a class="close-sidebar" href="http://google.com" target="_blank">google</a><br /><br />
	    <a class="close-sidebar" href="http://google.com" target="_blank">google</a>
	</td>
    </tr>
</table>
```
Plus table must not be use for layout, they are meant to hold data such as in spreadsheets. Consider not to use tables at all since they are hard to tweak and almost always break layouts. (If you need more reason not to use tables, I won't provide you them, google it).

Try to add a higher `zIndex` in the plugin method! See [options](https://github.com/dcdeiv/simpler-sidebar#options).

The last thing I can think of is to check for mistakes in your CSS file.

Consider to check [test](https://github.com/dcdeiv/simpler-sidebar/tree/master/tests) pages.

**Comment by cope** [comment]
I did follow the instructions and the cursor is default on links so no css tweaking is required as long as the links are in front, but they aren't because the mask if over them for some reason.

It could very well be a browser issue, I don't know.

All I know is that I finally gave up and wrote up my own slidebar, so I will continue with that one now...
