### ISSUE TITLE
Resize Issue

### ISSUE THREAD

**Issue by donenvy** [dcdeiv/simpler-sidebar#7]
Hi I liked your plugin but noticed a few things not sure if it is a bug.

1. On Samsung S6 on Firefox 39 if you switch from Vertical to horizontal view, the menu closes means you have to click the button again otherwise menu disappears
2. When in horizontal view, if the menu is long you can't scroll down to see the bottom of the menu is cut off. Although the background page scrolls, this menu doesn't so you can't select the bottom menu

**Comment by dcdeiv** [comment]
You have to add a wrapper. Read carefully the Getting Started guide [here](https://github.com/dcdeiv/simpler-sidebar/blob/master/README.md#getting-started).

In this plug-in the wrapper is [not supported](https://github.com/dcdeiv/simpler-sidebar/blob/master/README.md#simpler-sidebar-vs-simple-sidebar) which means that I will no longer provide a wrapper to let the content overflow because of some unfixable ajax issue. So you have to do it on your own. Read the guide.

**Comment by donenvy** [comment]
ah right, I was trying out your demo here http://dcdeiv.github.io/simpler-sidebar/. Does the issue exist here also?

**Comment by dcdeiv** [comment]
This is a CSS issue and it is fixed as it is written in the [Getting Started guide](https://github.com/dcdeiv/simpler-sidebar/blob/master/README.md#getting-started):

```html
.sidebar-wrapper {
    position: relative;
    height: 100%;
    overflow: auto;
}
```

**Comment by dcdeiv** [comment]
1. The sidenav closes itself when you change the screen orientation because it is safer than to leave it opened, maybe I could find a way to leave it opened in the next version;
2. The website was changed and updated recently, I forgot to add the CSS attribute you can find in the [Getting Started guide](https://github.com/dcdeiv/simpler-sidebar/blob/master/README.md#getting-started). Please, try again the demo!

**Comment by dcdeiv** [comment]
I fixed this issue. If you want to give it a try, you can download the pre-release [here](https://github.com/dcdeiv/simpler-sidebar/tree/resize-fix) or directly [here](https://github.com/dcdeiv/simpler-sidebar/tree/resize-fix/dist).

This fix will be pushed and released on 2015-08-25.
